---
- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Clear Mason cache
  ansible.builtin.file:
    path: /opt/rt4/var/mason_data/obj
    state: absent
  notify: Restart Apache
